version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    webserver:
        image: nginx:latest
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: muster_dikson_db
            MYSQL_PASSWORD:
            MYSQL_USER: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:
        driver: local

networks:
    laravel:
        driver: bridge
