version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/apache/Dockerfile
        container_name: filament_app
        ports:
            - "8080:80"
        volumes:
            - ./your-filament-project-files:/var/www/html
        depends_on:
            - php
            - db

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: filament_php
        volumes:
            - ./your-filament-project-files:/var/www/html
        working_dir: /var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public

    db:
        image: mysql:8.0
        container_name: filament_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: filament
            MYSQL_USER: filamentuser
            MYSQL_PASSWORD: filamentpassword
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: filament_phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword

volumes:
    db_data:
